<Project>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <!-- NuGet -->
    <IsAotCompatible>true</IsAotCompatible>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsPackable>false</IsPackable>
    <Version>1.1.0</Version>
    <Authors>guitarrapc</Authors>
    <Copyright>© guitarrapc</Copyright>
    <PackageTags>pty</PackageTags>
    <PackageVersion>$(Version)</PackageVersion>
    <PackageProjectUrl>https://github.com/guitarrapc/MiniPty</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>$(PackageProjectUrl)</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin/**;obj/**</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(WSL_DISTRO_NAME)' != '' and '$(HOME)' != ''">
    <BaseOutputPath>$(HOME)/.cache/minipty/msbuild/$(MSBuildProjectName)/bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(HOME)/.cache/minipty/msbuild/$(MSBuildProjectName)/obj/</BaseIntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" />
    <EmbeddedResource Include="$(MSBuildThisFileDirectory)LICENSE" />
  </ItemGroup>
</Project>
